apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-todoapi
  namespace: apm-apps
  labels:
    tags.datadoghq.com/env: "apm-apps"
    tags.datadoghq.com/service: "dotnet-todoapi"
    tags.datadoghq.com/version: "v1.0.0"
spec:
  selector:
    matchLabels:
      app: dotnet-todoapi
  template:
    metadata:
      labels:
        app: dotnet-todoapi
        tags.datadoghq.com/env: "apm-apps"
        tags.datadoghq.com/service: "dotnet-todoapi"
        tags.datadoghq.com/version: "v1.0.0"
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/dotnet-lib.version: "v3.17.0"
    spec:
      containers:
      - name: dotnet-todoapi
        image: ambrosiaaaaa/apm-dotnet:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env: 
          - name: DD_LOGS_INJECTION
            value: "true"
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi 