apiVersion: v1
kind: Service
metadata:
  name: dotnet-todoapi
  namespace: apm-apps
spec:
  type: ClusterIP
  selector:
    app: dotnet-todoapi
  ports:
  - name: http
    port: 8081
    targetPort: 80 