apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apm-apps
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/git-branch: "main"
    argocd-image-updater.argoproj.io/image-list: "dotnet=ambrosiaaaaa/apm-dotnet:v0.0.2,java=ambrosiaaaaa/apm-java:v0.0.2,python=ambrosiaaaaa/apm-python:v0.0.2"
    argocd-image-updater.argoproj.io/update-strategy: "latest"
    argocd-image-updater.argoproj.io/pull-secret: "dockerhub-secret"
    argocd-image-updater.argoproj.io/write-back-method: "git:secret:argocd/git-creds"
    argocd-image-updater.argoproj.io/write-back-target: "kustomization"
spec:
  project: default
  source:
    repoURL: https://github.com/tbernacchi/datadog-lab.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: apm-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - Validate=false 
