apiVersion: kustomize.config.k8s.io/v1beta1
images:
  - name: ambrosiaaaaa/apm-dotnet
    newTag: v0.0.3
  - name: ambrosiaaaaa/apm-java
    newTag: v0.0.3
  - name: ambrosiaaaaa/apm-python
    newTag: v0.0.3
