apiVersion: v1
kind: Service
metadata:
  name: python-flask
  namespace: apm-apps
spec:
  type: ClusterIP
  selector:
    app: python-flask
  ports:
  - name: http
    port: 8083
    targetPort: 5000 