apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-spring
  namespace: apm-apps
  labels:
    tags.datadoghq.com/env: "apm-apps"
    tags.datadoghq.com/service: "java-spring"
    tags.datadoghq.com/version: "v1.0.0"
spec:
  selector:
    matchLabels:
      app: java-spring
  template:
    metadata:
      labels:
        app: java-spring
        tags.datadoghq.com/env: "apm-apps"
        tags.datadoghq.com/service: "java-spring"
        tags.datadoghq.com/version: "v1.0.0"
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/java-lib.version: "v1.12.0"
    spec:
      containers:
      - name: java-spring
        image: ambrosiaaaaa/apm-java:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
          - name: DD_LOGS_INJECTION
            value: "true"
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi 