name: Build and push python image - kaniko

on:
  push:
    branches: [ main ]
    paths:
      - "apm/python/**"
      - ".github/workflows/build-with-kaniko.yml"

  workflow_dispatch:

env:
  REGISTRY_USER: ambrosiaaaaa
  REGISTRY: docker.io
  IMAGE_NAME: apm-python
  KANIKO_CACHE_ARGS: "--cache=true --cache-ttl=24h"

jobs:
  build-and-push:
    runs-on: my-runner-datadog-lab # my self-hosted runner
    container:
      image: gcr.io/kaniko-project/executor:latest

    permissions:
      contents: read

    steps:
      - name: Build and Push Image to Docker Hub with Kaniko
        run: |
          mkdir -p /kaniko/.docker
          cat <<EOF > /kaniko/.docker/config.json
          {
            "auths": {
              "https://index.docker.io/v1/": {
                "auth": "$(echo -n "${{ env.REGISTRY_USER }}:${{ secrets.DOCKERHUB_TOKEN }}" | base64 -w0)"
              }
            }
          }
          EOF

          /kaniko/executor \
            --dockerfile=apm/python/Dockerfile \
            --context=dir://./apm/python \
            --destination=${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:$(echo $GITHUB_SHA | head -c 7) \
            ${{ env.KANIKO_CACHE_ARGS }} \
            --push-retry 5
