name: Build and push python image - DinD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY_USER: ambrosiaaaaa
  REGISTRY: docker.io
  IMAGE_NAME: apm-python

jobs:
  python-build:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: [my-runner-datadog-lab] # teu runner no k8s

    defaults:
      run:
        working-directory: apm/python

    services:
      docker:
        image: docker:24.0.2-dind
        privileged: true
        options: --network host
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker client
        run: |
          apk add --no-cache docker-cli
          export DOCKER_HOST=tcp://localhost:2375
          docker version

      - name: Read version from file
        id: version
        run: |
          VERSION=$(cat .version)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Install Python dependencies
        run: |
          apk add --no-cache python3 py3-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Run tests if exist
        run: |
          TEST_FILES=$(find . -name "test_*.py" -o -name "*_test.py")
          if [ -z "$TEST_FILES" ]; then
            echo "Warning: No test files found, skipping tests."
          else
            echo "Found test files:"
            echo "$TEST_FILES"
            python3 -m pytest -v
          fi

      - name: Login to Docker Hub
        run: |
          export DOCKER_HOST=tcp://localhost:2375
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u $REGISTRY_USER --password-stdin $REGISTRY

      - name: Build and push image with Docker
        run: |
          export DOCKER_HOST=tcp://localhost:2375
          VERSION=${{ steps.version.outputs.VERSION }}
          IMAGE=$REGISTRY/$REGISTRY_USER/$IMAGE_NAME:$VERSION
          docker build -t $IMAGE .
          docker push $IMAGE
