name: Build and push python image - kaniko

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY_USER: ambrosiaaaaa
  REGISTRY: docker.io
  IMAGE_NAME: apm-python

jobs:
  python-build:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: my-runner-datadog-lab

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read version from file
        id: version
        run: |
          VERSION=$(cat apm/python/.version)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Install Python dependencies
        working-directory: apm/python
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Run tests if exist
        working-directory: apm/python
        run: |
          TEST_FILES=$(find . -name "test_*.py" -o -name "*_test.py")
          if [ -z "$TEST_FILES" ]; then
            echo "Warning: No test files found, skipping tests."
          else
            echo "Found test files:"
            echo "$TEST_FILES"
            python3 -m pytest -v
          fi

      - name: Build and push with Kaniko
        uses: aevea/action-kaniko@master
        with:
          image: ${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          path: ./apm/python
          tag: ${{ steps.version.outputs.VERSION }}
          registry: ${{ env.REGISTRY }}
