name: Build and push python image - kaniko

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY_USER: ambrosiaaaaa
  REGISTRY: docker.io
  IMAGE_NAME: apm-python

jobs:
  python-build:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apm/python

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Kaniko
        run: |
          sudo mkdir -p /kaniko
          sudo curl -Lo /kaniko/executor https://storage.googleapis.com/kaniko-releases/v1.20.0/executor-linux-arm64
          sudo chmod +x /kaniko/executor
        working-directory: /

      - name: Read version from file
        id: version
        run: |
          VERSION=$(cat .version)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Run tests if exist
        run: |
          TEST_FILES=$(find . -name "test_*.py" -o -name "*_test.py")
          if [ -z "$TEST_FILES" ]; then
            echo "Warning: No test files found, skipping tests."
          else
            echo "Found test files:"
            echo "$TEST_FILES"
            python3 -m pytest -v
          fi

      - name: Login to DockerHub for Kaniko
        run: |
          sudo mkdir -p /kaniko/.docker
          sudo cat <<EOF > /kaniko/.docker/config.json
          {
            "auths": {
              "${{ env.REGISTRY }}": {
                "username": "${{ env.REGISTRY_USER }}",
                "password": "${{ secrets.DOCKERHUB_TOKEN }}"
              }
            }
          }
          EOF
        working-directory: /

      - name: Build and push with Kaniko
        run: |
          sudo /kaniko/executor \
            --dockerfile=Dockerfile \
            --context=dir://$(pwd) \
            --destination=${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }} \
            --skip-tls-verify
