name: Build and push python image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY_USER: ambrosiaaaaa
  REGISTRY: docker.io

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-build:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: my-runner-datadog-lab
    container:
      image: quay.io/buildah/stable:latest
      options: --privileged
    
    env:
      IMAGE_NAME: apm-python
      RUNNER_TOOL_CACHE: "/tmp/runner"
      ACTIONS_CACHE_URL: ""
      ACTIONS_RUNTIME_URL: ""

    defaults:
      run:
        working-directory: apm/python

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Python
        run: |
          microdnf install -y python3 python3-pip
          python3 -m pip install --upgrade pip

      - name: Read version from file
        id: version
        run: |
          VERSION=$(cat .version)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Check and run tests
        run: |
          TEST_FILES=$(find . -name "test_*.py" -o -name "*_test.py")
          if [ -z "$TEST_FILES" ]; then
            echo "Warning: No test files found, skipping tests."
          else
            echo "Found test files:"
            echo "$TEST_FILES"
            python3 -m pytest -v
          fi

      - name: Build and push with buildah
        run: |
          VERSION=${{ steps.version.outputs.VERSION }}
          IMAGE=$REGISTRY/$REGISTRY_USER/$IMAGE_NAME:$VERSION
          buildah bud -t $IMAGE .
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | buildah login -u "$REGISTRY_USER" --password-stdin "$REGISTRY"
          buildah push $IMAGE
